name: Update Flake Version

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  update-flake:
    name: Update version and hash in flake.nix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Extract release tag version
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Update version in flake.nix
        run: |
          sed -i "s/version = \".*\";/version = \"${VERSION}\";/" flake.nix
          echo "Updated version in flake.nix to ${VERSION}"

      - name: Calculate correct pnpmDeps hash
        id: calc_hash
        run: |
          nix_prefetch_output=$(nix build --print-out-paths .#packages.x86_64-linux.default 2>&1 || true)
          HASH=$(echo "$nix_prefetch_output" | grep -o 'got:.*' | awk '{print $2}')
          if [ -z "$HASH" ]; then
            echo "Failed to extract hash"
            exit 1
          fi
          echo "HASH=$HASH" >> $GITHUB_ENV
          echo "New hash: $HASH"

      - name: Update hash in flake.nix
        run: |
          sed -i "s|hash = \"sha256-[A-Za-z0-9+/=]*\";|hash = \"$HASH\";|" flake.nix
          echo "Updated hash in flake.nix"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update flake.nix to version ${{ env.VERSION }} with new hash"
          title: "Update flake.nix to version ${{ env.VERSION }}"
          body: |
            This PR updates flake.nix with:
            - New version: ${{ env.VERSION }}
            - New hash: ${{ env.HASH }}

            This update was performed automatically by a GitHub workflow.
          branch: update-flake-version-${{ env.VERSION }}
          base: main
          delete-branch: true
